apiVersion: v1
kind: Service 
metadata:
  name: calculator-1-service
spec:
  type: ClusterIP
  selector:
    app: calculator-1
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 5000 # Container Port
---
apiVersion: v1
kind: Service 
metadata:
  name: calculator-2-service
spec:
  type: ClusterIP
  selector:
    app: calculator-2
  ports: 
    - name: http
      port: 5000 # Service Port
      targetPort: 5000 # Container Port
---
apiVersion: v1
kind: Service 
metadata:
  name: calculator-3-service
spec:
  type: ClusterIP
  selector:
    app: calculator-3
  ports: 
    - name: http
      port: 5000 # Service Port
      targetPort: 5000 # Container Port
---
