# Simple Key value Pairs
person: # Dictionary
  name: atingupta
  age: 39
  city: NCR
  hobbies: # List
    - cooking
    - cycling
  friends: # Multiple lists
    - name: friend1
      age: 39
    - name: friend2
      age: 22
--- # YAML Document Separator
apiVersion: v1 # String
kind: Pod  # String
metadata: # Dictionary
  name: myapp-pod
  labels: # Dictionary 
    app: myapp    
    tier: frontend     
spec:
  containers: # List
    - name: myapp
      image: atingupta2005/kubenginx:1.0.0
      ports: # List
        - containerPort: 80
          protocol: "TCP"
        - containerPort: 81
          protocol: "TCP"  


                     

  