# Configures the SELinux mode and policy.
# SELinux is designed to protect against misuse and unauthorized use such as: Unauthorized reading of data and programs. Unauthorized modification of data and
# SELinux can operate in two global modes: Permissive mode, in which permission denials are logged but not enforced. Enforcing mode, in which permissions denials are both logged and enforced.
# programs.
- name: Se Linux
  hosts: all
  gather_facts: false
  tasks:
    - name: Updating repos
      apt:
        name: "*"
        state: latest
    - name: Installing python pip
      apt:
        name: python3-pip
        state: present
    - name: Installing python selinux
      command: pip install selinux

    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: default
        state: permissive
    
    #- name: Disable SELinux
    #  ansible.posix.selinux:
    #    state: disabled