---
- hosts: localhost
  gather_facts: false
  tasks:
    - shell: "bash --version"
      register: bash_ver
    - set_fact: # To define a new variable simply
        bash_version: "{{bash_ver.stdout.split('\n')[0].split()[3]}}"
        my_value: "bash version" # Another variable
    - debug: var=bash_version
