---
- hosts: all
  gather_facts: false
  tasks:
    - debug:
        msg:
          - "The x value is: {{x}}"
          - "The y value is: {{y}}"
# How to run:
# ansible-playbook 31.Working-with-command-line-arguements.yml
# ansible-playbook 31.Working-with-command-line-arguements.yml  -e "x=45"
# ansible-playbook 31.Working-with-command-line-arguements.yml  --extra-var "x=45"
# ansible-playbook 31.Working-with-command-line-arguements.yml  --extra-var "{ 'x':  45 }"
# ansible-playbook 31.Working-with-command-line-arguements.yml  --extra-var "{ 'x':  45, 'y': 67 }"
# ansible-playbook 31.Working-with-command-line-arguements.yml  -e "x=45 y=67"
# ansible-playbook 31.Working-with-command-line-arguements.yml  -e "x=45 y='Ansible Playbooks'"
# ansible-playbook 31.Working-with-command-line-arguements.yml  --extra-var "{ 'x':  45, 'y': 'Ansible Playbooks' }"
# ansible-playbook 31.Working-with-command-line-arguements.yml  --extra-var "{ 'x':  45, 'y': [4,5,6,78,1] }"
# ansible-playbook 31.Working-with-command-line-arguements.yml  --extra-var "{ 'x':  45, 'y': {'one': 1, 'two': 2, 'three': 3} }"

# ansible-playbook 31.Working-with-command-line-arguements.yml  --extra-var "@variables_values.yml"
