---
- name: This is the simple play to understand debug module
  hosts: all
  tasks:
    - name: Printing a msg with msg parameter of debug module 1
      debug: msg="Welcome to Ansible Playbooks"
    - name: Printing a msg with msg parameter of debug module 2
      debug:
        msg: "Welcome to Ansible Playbooks"
    - name: Printing a msg with msg parameter of debug module 3
      debug:
        msg:
          - "Welcome to Ansible Playbooks"
          - "These are basic concepts"
          - "We will do advanced as well"
