global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "vmwin-prometheus-client1"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["vmwin-prometheus-client1.eastus.cloudapp.azure.com:9182"]

  - job_name: "vmubuntu-prometheus-client1"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["vmubuntu-prometheus-client1.eastus.cloudapp.azure.com:9100"]

  - job_name: "vmubuntu-prometheus-client1-python"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["vmubuntu-prometheus-client1.eastus.cloudapp.azure.com:8000"]

  - job_name: "file sd"
    file_sd_configs:
      - files:
          - file_sd/*.yml

rule_files:
  - "rules.yml"
