# Check if a file exists on Windows-like systems
---
- name: check if a file exist
  hosts: all
  vars:
    myfile: 'C:\example.txt'
  tasks:
    - name: check if a file exist
      ansible.windows.win_stat:
        path: "{{ myfile }}"
      register: file_data

    - name: report file exist
      ansible.builtin.debug:
        msg: "The file {{ myfile }} exist"
      when: file_data.stat.exists

    - name: report file not exist
      ansible.builtin.debug:
        msg: "The file {{ myfile }} doesn't exist"
      when: not file_data.stat.exists
