kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: calculator-1-service
spec:
  hosts:
    - "*"
  http:
    - match:
        - headers:
            x-my-header:
              exact: release-v2
      route:
        - destination:
            host: calculator-1-service
            subset: v2
    - route:
        - destination:
            host: calculator-1-service
            subset: v1
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: calculator-1-service
spec:
  host: calculator-1-service
  subsets:
    - labels:
        version: v1
      name: v1
    - labels:
        version: v2
      name: v2
