apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: atingupta2005/winsqlserver
        env:
        - name: sa_password
          value: "KjIp#mnj123"
        - name: ACCEPT_EULA
          value: "Y"
        ports:
        - containerPort: 1433