---
- hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
      notify:
        - start nginx
  handlers:
    - name: start nginx
      service: name=nginx state=restarted
