---
- hosts: all
  become: yes
  gather_facts: false
  vars:
    version_number: 1
    server: my_server
    x: 56
    y: 78
  tasks:
    - name: Example Template
      template:
        src: example_template.j2
        dest: example_file.txt
      register: template_output
    - debug: var=template_output
# How to run:
# ansible-playbook 1.Creating-template-files.yml
# cat  ~/example_file.txt
