# Extract an archive in Windows-like systems
---
- name: win_unzip module demo
  hosts: all
  become: false
  vars:
    mysrc: 'C:\example.zip'
    mydest: 'C:\output'
  tasks:
    - name: extract archive
      community.windows.win_unzip:
        src: "{{ mysrc }}"
        dest: "{{ mydest }}"
