#!/usr/bin/ansible-playbook
- name: Usage of Debug Module
  hosts: all
  tasks:
    - name: Printing a variable value using Debug Module - msg
      debug:
        msg: "The host name is: {{inventory_hostname}}"
    - name: Printing a variable value using Debug Module - var
      debug:
        var: inventory_hostname
# How to run:
# chmod +x "24-Print-Variable-Value.yml"
# ./24-Print-Variable-Value.yml
